.PHONY: lock lock-check help

# Bash for `<()` process substitution in lock-check.
SHELL := /bin/bash

# `make lock` regenerates `requirements-dev.lock` from
# `pyproject.toml`'s [project.optional-dependencies].dev. Run this
# whenever a dev dep is added, removed, or version-bumped — CI
# installs from the lockfile, so a stale lock means CI will not see
# manifest changes.
#
# Uses an isolated venv at `.venv-lock` so pip-tools does not
# pollute `.venv` (the dev environment used by `maturin develop`).
lock:
	@python3 -m venv .venv-lock
	@.venv-lock/bin/pip install --quiet --upgrade pip pip-tools
	@.venv-lock/bin/pip-compile pyproject.toml --extra dev \
		--output-file=requirements-dev.lock --resolver=backtracking --quiet
	@rm -rf .venv-lock
	@echo "regenerated requirements-dev.lock"

# `make lock-check` verifies the committed lockfile is up to date
# with `pyproject.toml`. Useful as a pre-push sanity check; not
# wired into CI yet — add a workflow step if drift becomes a
# recurring issue.
lock-check:
	@python3 -m venv .venv-lock-check
	@.venv-lock-check/bin/pip install --quiet --upgrade pip pip-tools
	@.venv-lock-check/bin/pip-compile pyproject.toml --extra dev \
		--output-file=.venv-lock-check/regenerated.lock \
		--resolver=backtracking --quiet
	@# Skip the first 6 lines of each file: pip-compile writes the
	@# `--output-file` path into an autogenerated header, so two
	@# otherwise-identical lockfiles compiled to different paths
	@# would always diff on that single line.
	@diff -u <(tail -n +7 requirements-dev.lock) <(tail -n +7 .venv-lock-check/regenerated.lock) \
		&& echo "lockfile is up to date" \
		|| (echo "lockfile is stale — run 'make lock'"; rm -rf .venv-lock-check; exit 1)
	@rm -rf .venv-lock-check

help:
	@echo "Targets:"
	@echo "  lock        Regenerate requirements-dev.lock from pyproject.toml"
	@echo "  lock-check  Verify requirements-dev.lock matches pyproject.toml"
